[package]
name = "twitter2_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twitter2 = { path = "../twitter2" }
tokio = { version = "1.24.2", features = ["full"] }
